### ISSUE TITLE
remove `rocket.Cookie` and `rocket.Header`

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/rocket#129]
This is related to #87, the reason is that of `rocket.Cookie` & `rocket.Header` didn't actually a good interface for getting data, so we plan to use **UserDefinedContext** replace them.

**Comment by dannypsnl** [comment]
@shana0440 I have two ideas, which one do you prefer?
```go
// Embedded
type UserContextWithCookie struct {
    rocket.Cookie
}
// Or filler
type UserContextWithCookie struct {
    Token *string `cookie:"token"`
}
```

**Comment by shana0440** [comment]
I prefer filler.

**Comment by dannypsnl** [comment]
Actually when we have a content in commit says “resolve xxx”, we would see GitHub close issue automatically by the commit into master and leave a reference here so we don’t have to do this manually XD
