### ISSUE TITLE
Mode switching

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/rocket#135]
The idea is we have `debug` mode and `production` mode, and users can use `+debug` flag to get verbose information when serving and get higher performance for the production environment.

**Comment by shana0440** [comment]
ok, what information we should provide?
I think we should provide the request body and request URL.
what do you think?

**Comment by dannypsnl** [comment]
I think we should provide emitted route when router start, and detail log when request in. Yes, I think body and URL is good idea

**Comment by dannypsnl** [comment]
Seems unneeded right now so close it

**Comment by dannypsnl** [comment]
Its conflicts with fairing part.
