### ISSUE TITLE
Add ContentType method on Response

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/rocket#154]
I found I hard to create a response with Spec content-type that not writing data at `New` part.

For example:
```go
response.
    Stream(func(w http.ResponseWriter) {
        w.Write(jsonData)
    })
```

**Comment by dannypsnl** [comment]
@shana0440 Do you think this makes sense?

**Comment by dannypsnl** [comment]
I have another idea is we make Json be `interface{}` and then we do real type assertion to automatic set content-type

**Comment by shana0440** [comment]
> I have another idea is we make Json be `interface{}` and then we do real type assertion to automatic set content-type

What do you mean automatic set `Content-Type`? I think we already set `Content-Type` automatically, aren't we?

**Comment by dannypsnl** [comment]
We can't do this with streaming, when we use streaming, some clients are requiring content-type but we can only use `Headers` to modify it, I believe it's hard for whos don't familiar with HTTP definition.

**Comment by shana0440** [comment]
Yes, I think we can introduce `ContentType` in our response package.

**Comment by dannypsnl** [comment]
- [ ] add this method to the official document, at response section

**Comment by dannypsnl** [comment]
#### TEXT

- `ContentType`, let you modify content-type of response easier(compare to setting __header__ directly)
```go
response.Stream(func(w http.ResponseWriter) {
    // ignore
}).
    ContentType("application/json")
```
