### ISSUE TITLE
Cache context offset in Mount time.

### ISSUE THREAD

**Issue by shana0440** [dannypsnl/rocket#155]
We cache context offset in setup HTTP method currently.
This cause filler needs to calculate basePathLen to get the real route params position.
And another issue is if we cache context offset in setup HTTP method, the user must set every route params in `rocket.Get(....)`, I think it will make every one mount handler in root path, then we will get a huge Mount function.
for example
```
getPost := rocket.Get(":user/posts/:post", ...);
createPost := rocket.Post(":user/posts/:post", ...);
getUser := rocket.Get(":user");
createUser := rocket.Post("/")

rocket.Moun("/user", getPost, createPost, getUser, createUser);
```
if any resource relate user then they will be put in base path `/user`.

**Comment by shana0440** [comment]
@dannypsnl 
How do you think if we remove base path of `Mount` and force the user must write the whole path when they create handler?
for example
```go
// origin
getUser := rocket.Get(":user", ...)
rocket.Mount("/users", getUser)
// after remove basePath of Mount
getUser := rocket.Get("/users/:user", ...)
rocket.Mount(getUser)
```

**Comment by dannypsnl** [comment]
How about adding Group this abstraction, so that we can avoid duplicate typing the base route?

**Comment by shana0440** [comment]
I want to avoid route separate in different places.
How does Group work?

**Comment by shana0440** [comment]
This relates to #176, move the discussion to #176
