### ISSUE TITLE
Remove a part of URL defined in Mount

### ISSUE THREAD

**Issue by shana0440** [dannypsnl/rocket#176]
Because our `Mount` doesn't allow route params, that cause our `Handler` cannot separate well.
for example, if we have two apis, `getUser` and `getPost`, this two apis should not be same group, but in our current design it will look like following code.
```go 
getUser := rocket.Get("/:user")
getPost := rocket.Get("/:user/posts/:post")
rocket.Mount(
  "/users", getUser, getPost
)
```
I think we should move our whole route to `Handler`, then above code will change like the following code.
```
rocket.Get("/users/:user")
rocket.Get("/users/:user/posts/:post")
```
The problem of this way is it will let user typing duplicate route continually. But the reason for I don't want to introduce route params to `Mount` is it will let the user keep looking route to realize the handler use how many route params and when the application grows, it will have more and more APIs, the route will growing and hard to read.

**Comment by dannypsnl** [comment]
What if we create an abstraction that looks like:
```go
var usersGroup = rocket.Group("/users", rocket.Routes{
    "/:user": rocket.Get(getUser),
    "/:user/posts/:post": rocket.Get(getPost),
}).Guard(&UserAuth{})

// at main package
rocket.Mount(usersGroup)
```

Where the benefit is we can avoid duplicate typing and keep route easy to read, and users still can manage routes in an easy way. And we apply `Guard` on a group, avoid missing apply on a single handler happened.

**Comment by shana0440** [comment]
If `Group` cannot allow route params, then it basically is similar to `Mount`.
And the other reason I don't like this solution is user cannot get all the information when the user looking handler.
If the user wants to know what user can access this handler, they need to go to route file to see there have any `Guard` and when the permission more complex, the user needs to switch the file constantly to understand the whole picture of this handler.

**Comment by dannypsnl** [comment]
Yes, I also have a similar concern about any shared things would make users harder to get what actually happened on the handler.

**Comment by dannypsnl** [comment]
@shana0440 Do you have any ideas about the new name of `Mount` after we change the signature?

**Comment by shana0440** [comment]
I considering two options.
1. remove `Mount`, mount handler when invoke `rocket.Get()`, `rocket.Post` .....
2. keep `Mount`, invoke it like the following code
```
rocket.Mount(
  rocket.Get(...),
  rocket.Post(...),
  ...handlers,
)
```
I think the second is better, it will make the handler more easy to test.

**Comment by dannypsnl** [comment]
What the problem is, second one would spread handler and handle function,
right? Aren’t you want to avoid that?

kw <notifications@github.com>於 2019年2月24日 週日，上午3:36寫道：

**Comment by shana0440** [comment]
I want to avoid the URL defined in different places, so we can reduce some context switch when we create or maintain the handler.
I don't think it will affect we maintain the handler if we use the second one.

**Comment by dannypsnl** [comment]
So basically we would get a new interface like:
```go
rocket.Ignite(":port").
    Mount(
        rocket.Get("/users/:id", getUserPage),
        rocket.Post("/users/:id/article", postNewArticle),
    )
```

@shana0440 Do I get it?

**Comment by shana0440** [comment]
Yes
