### ISSUE TITLE
static file mime type

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/rocket#41]
A common way about using a variant route is for static files in the project.
Then how to decide file's mime type would be an important issue.

**Comment by dannypsnl** [comment]
e.g.
```go
type FileRequest struct {
    Path string `route:"path"`
}
var (
    staticFiles = rocket.Get("/*path", func(file *FileRequest) string {
        content, err := ioutil.ReadFile("./static/" + file.Path)
	if err != nil {
		log.Fatal(err)
	}
        return string(content)
    })
)
```

**Comment by dannypsnl** [comment]
@shana0440 So, do we need file module now? Or use `Response` support it

**Comment by dannypsnl** [comment]
Remove from v0.12.0 milestone, response can handle basic requirements now.

**Comment by dannypsnl** [comment]
Maybe can use third party lib to do content detecting, e.g. https://github.com/gabriel-vasile/mimetype

**Comment by shana0440** [comment]
yes, it will make thing easier.
