### ISSUE TITLE
Middleware discussion

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/rocket#57]
Create for discussion about how to create middleware

**Comment by shana0440** [comment]
Do you think the "fairings" is the good way to deal with it?
this is the discussion on rocket-ts https://github.com/SergioBenitez/Rocket/issues/55

**Comment by dannypsnl** [comment]
- Option 1: Fairing + handlerHandler
- Option 2: context type + classic middleware(Express.js style)

**Comment by dannypsnl** [comment]
After discussion, use fairing.
