### ISSUE TITLE
[Feature] Fairing

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/rocket#60]
A fairing is some rules would be triggered on some timer.
The fairing will own some handlers, so these handlers life cycle would be controlled by this fairing.

- [x] OnResponse
- [x] OnRequest

**Comment by dannypsnl** [comment]
Basically, to avoid fairing became too complex, it should only handle cookie, header & response

**Comment by dannypsnl** [comment]
Now problem is, request fairing could need to notify user handler or directly modified response, both aren't the reason we create fairing.

- Notify: Break the only handle once this purpose
- Modified: Break couldn't overuse fairing this purpose

**Comment by shana0440** [comment]
Seem the idea of fairing cannot achieve our goal.
Do you think we should use `ResponseDecorator` and `RequestGuarder` to replace fairing?

**Comment by dannypsnl** [comment]
I think just use guard to do auth, fairing is ok actually.
