### ISSUE TITLE
Optional field

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/rocket#86]
The handler should return **HTTP Code 400** if can't fill user-defined context, but if a field is a pointer, that means the field is omittable(but if it is a type error, still have to return **400**)

**Comment by dannypsnl** [comment]
The idea is, `parseParameter` returns an error if it's not a pointer(represents omissible) or types mismatched. `context` catch the error then return it, if receive an error, `Handle` should set status to **400**

**Comment by shana0440** [comment]
I don't like the idea to use the pointer to intend the field is optional.
because it not obvious to me.

**Comment by dannypsnl** [comment]
I think better to use tag with pointer, pointer is important because go has zero value this feature, it would cause people who doesn't familiar with Go write the wrong thing
